---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: open-ai-api-key
    category: Custom
spec:
  extends:
    - name: extension-definition
  properties:
    api_key:
      description: The API Key from open ai. It will use one from the list so that it avoids hitting rate limit
      type: array
      items:
        type: string
  required:
    - api_key
